dahu/frontend/forms.py
# -*- coding: utf-8 -*-

'''
Dahu: Picture gallery
Licence: BSD (see LICENCE file)

Author: Damien Riquet <d.riquet@gmail.com>
Description:
    Web forms
'''

from flask.ext.wtf import Form, TextField, PasswordField, Required

class LoginForm(Form):
    username = TextField('Username', validators=[Required(message='Username is required.')])
    password = PasswordField('Password', validators=[Required(message='Password is required.')])

dahu/frontend/views.py
# -*- coding: utf-8 -*-

'''
Dahu: Picture gallery
Licence: BSD (see LICENCE file)

Author: Damien Riquet <d.riquet@gmail.com>
Description:
    Views for the web frontend
'''

import os
from functools import wraps
from flask import Blueprint, current_app, abort, render_template, send_from_directory, request, session, url_for, redirect
from dahu.core import album, image, permission
from dahu.frontend import context, forms

frontend = Blueprint('frontend', __name__, template_folder='templates')

def render_theme(template, **kwargs):
    template_path = os.path.join(current_app.config['FRONTEND_THEME'], template)
    return render_template(template_path, **kwargs)

def get_argument(name):
    if request.args.get(name): return request.args.get(name)
    if name in session: return session[name]
    return ''

def login_required(f):
    @wraps(f)
    def decorated_function(album_path, *args, **kwargs):
        p_config = permission.get_config(current_app.config['CACHE_PATH'], 'permissions.json')

        if request.args.get('album_key'):
            session['album_key'] = request.args.get('album_key')
        album_key = session['album_key'] if session.has_key('album_key') else ''

        if not 'username' in session:
            if not permission.is_public_album(p_config, album_path) and \
            not permission.check_album_key(p_config, album_path, album_key):
                abort(404)

        return f(album_path, *args, **kwargs)
    return decorated_function


@frontend.errorhandler(404)
def page_not_found(e):
    return render_theme('404.html'), 404


@frontend.route('/login/', defaults={'album_path':''}, methods=['GET', 'POST'])
@frontend.route('/login/<path:album_path>', methods=['GET', 'POST'])
def login(album_path):
    if session.has_key('username'):
        return redirect(url_for('.show_album', album_path=album_path))
    form = forms.LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        p_config = permission.get_config(current_app.config['CACHE_PATH'])
        if permission.check_user_pwd(p_config, form.username.data, form.password.data):
            session['username'] = request.form['username']
            return redirect(url_for('.show_album', album_path=album_path))
    return render_theme('login.html', album_path=album_path, form=form)


@frontend.route('/logout/')
def logout():
    if session.has_key('username'):
        session.pop('username', None)
    return redirect(url_for('.show_album'))


@frontend.route('/', defaults={'album_path':''})
@frontend.route('/albums/<path:album_path>')
@login_required
def show_album(album_path):
    if not album.is_valid_path(current_app.config['ALBUMS_PATH'], album_path):
        abort(404)

    album_context = context.generate_album_context(album_path)
    return render_theme('album.html', **album_context)


@frontend.route('/image/<path:album_path>/<filename>/', defaults={'size':None})
@frontend.route('/image/<path:album_path>/<filename>/<size>/')
@login_required
def get_image(album_path, filename, size=None):
    image_retrieved = image.get_image(current_app.config['ALBUMS_PATH'], current_app.config['CACHE_PATH'], album_path, filename, size)
    if image_retrieved:
        return send_from_directory(*image_retrieved)
    abort(404)


@frontend.route('/image/thumb/<path:album_path>/<filename>/')
@login_required
def get_thumb(album_path, filename):
    thumb_retrieved = image.get_image(current_app.config['ALBUMS_PATH'], current_app.config['CACHE_PATH'], \
        album_path, filename, current_app.config['PICTURE_THUMBNAIL_SIZE'], thumbnail=True)
    if thumb_retrieved:
        return send_from_directory(*thumb_retrieved)
    abort(404)


@frontend.route('/albums/thumb/<path:album_path>/')
@login_required
def get_album_thumb(album_path):
    album_thumb = album.get_album_thumbnail(current_app.config['ALBUMS_PATH'], current_app.config['CACHE_PATH'], \
        album_path, current_app.config['ALBUM_THUMBNAIL_SIZE'])
    if album_thumb:
        return send_from_directory(*album_thumb)
    abort(404)


@frontend.route('/static_files/<path:filename>')
def static_files(filename):
    """ Deals with static files (like css and js) """
    static_path = os.path.join(frontend.root_path, 'templates', current_app.config['FRONTEND_THEME'], 'static')
    return send_from_directory(static_path, filename)

dahu/frontend/templates/default/album.html
{% extends "default/base.html" %}

{% block content %}
<!-- Inner albums -->

<div class="container">
    {% for column in inner_albums|batch(3) %}
        <ul class="thumbnails">
        {% for album in column %}
            <li class="span4">
                <div class="thumbnail" style="padding-top:10px;">
                    <a href="{{ album.link }}">
                    <img src="{{ url_for('.get_album_thumb', album_path=album.path) }}" />
                    <h5>{{ album.name }}</h5>
                    </a>
                    <p>{{ album.total_nb_pictures }} images</p>
                </div>
            </li>
        {% endfor %}
        </ul>
    {% endfor %}
</div>

<!-- Pictures gallery -->
<div class="yoxview">
    <ul class="thumbnails">
        {% for picture in pictures %}
            <li>
            <a
                class="thumbnail"
                href="{{ url_for('.get_image', album_path=name, filename=picture, size=config.PICTURE_SLIDESHOW_SIZE) }}">
                <img src="{{ url_for('.get_thumb', album_path=name, filename=picture) }}" title="{{ picture }}" />
            </a>
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}


{% block js_include %}
    <!-- jQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <!-- yoxview -->
    <script src="{{ url_for('frontend.static_files', filename='yoxview/yoxview-init.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".yoxview").yoxview({
                allowedUrls: /.*/i,
                buttonsFadeTime: 0
            });
        });
    </script>
{% endblock %}

dahu/frontend/templates/default/base.html
<!DOCTYPE html>
<html lang="en">
    <head>

        <!-- start: Meta -->
        <meta charset="utf-8">
        <title>{% block title %}{{ config.GALLERY_TITLE }}{% endblock %}</title>
        <!-- end: Meta -->

        <!-- start: Mobile Specific -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <!-- end: Mobile Specific -->


        <!-- start: CSS -->
        <link href="{{ url_for('frontend.static_files', filename='css/bootstrap-responsive.min.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ url_for('frontend.static_files', filename='css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ url_for('frontend.static_files', filename='css/style.css') }}" rel="stylesheet" type="text/css">
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
        <!-- end: CSS -->

    </head>

    <body>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="{{ url_for('.show_album', album_path='') }}">{{ config.GALLERY_NAME }}</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                        </ul>
                    </div>
                    <p class="navbar-text pull-right">
                        {% if session.username %}
                        <a href="{{ url_for('.logout') }}" >
                            logout <i class="icon-off icon-white"></i>
                        </a>
                        {% else %}
                        <a href="{{ url_for('.login') }}" >
                            login <i class="icon-user icon-white"></i>
                        </a>
                        {% endif %}
                    </p>
                </div>
            </div>

        </div>


        <div class="container">

            {% if linked_path %}
            <ul class="breadcrumb">
                {% for album, link in linked_path %}
                    {% if loop.last %}
                        <li class="active">{{ album }}</li>
                    {% else %}
                        <li><a href="{{ link }}">{{ album }}</a> <span class="divider">/</span></li>
                    {% endif %}
                {% endfor %}
            </ul>
            {% endif %}

            {% block content %}
            {% endblock %}

            <div class="row-fluid">
                <div id="footer" class="span12">
                    Proudly powered by <a href="https://github.com/driquet/dahu">Dahu</a>,
                    which takes great advantage of <a href="http://python.org/">Python</a>,
                    <a href="http://flask.pocoo.org/">Flask</a> and <a href="http://twitter.github.io/bootstrap/">Bootstrap</a>.
                </div>
            </div>

        </div>


        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{{ url_for('frontend.static_files', filename='js/bootstrap.min.js') }}"></script>
        {% block js_include %}{% endblock %}
    </body>
</html>

dahu/frontend/templates/default/login.html
{% extends "default/base.html" %}

{% block content %}

<div id="container">
    <form class="log-form"action="{{ url_for('frontend.login', album_path=album) }}" method="post">
        <h1>Login</h1>
        {{ form.csrf_token }}
        {% if form.username.errors or form.password.errors %}
            <div class="alert alert-error" style="padding-bottom:10px;">
                <ul class="unstyled" style="margin-bottom:0px;">
                {% for error in form.username.errors %}<li>{{ error }}</li>{% endfor %}
                {% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}
                </ul>
            </div>
        {% endif %}
        <div class="input-prepend">
            <span class="add-on"><i class="icon-user"></i></span>
            <input class="input-xlarge" type="text" placeholder="Username" name="username">
        </div>
        <div class="input-prepend">
            <span class="add-on"><i class="icon-lock"></i></span>
            <input class="input-xlarge" type="password" placeholder="Password" name="password">
        </div>

        <button class="btn pull-right" type="submit">Login</button>
        <hr></hr>

        <h4>Forget your password ?</h4>
        <p>No worries, contact the webmaster to reset it !</p>
    </form>
</div>

{% endblock %}